# Generated by Django 4.2 on 2025-01-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagarija'), ('P', 'Planta'), ('T', 'Tierra'), ('F', 'Fuego'), ('A', 'Agua'), ('E', 'Electrico')], max_length=30),
        ),
    ]
