# Generated by Django 4.2 on 2025-01-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('F', 'Fuego'), ('E', 'Electrico'), ('T', 'Tierra'), ('L', 'Lagarija'), ('A', 'Agua')], max_length=30),
        ),
    ]
